#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Sep 25 11:23:47 MDT 2026
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim lab_1b_top_level_tb_time_impl -key {Post-Implementation:sim_1:Timing:lab_1b_top_level_tb} -tclbatch lab_1b_top_level_tb.tcl -log simulate.log"
xsim lab_1b_top_level_tb_time_impl -key {Post-Implementation:sim_1:Timing:lab_1b_top_level_tb} -tclbatch lab_1b_top_level_tb.tcl -log simulate.log

